main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("pokemon/", views.index, name="pokemon-index"),
    path("pokemon/<int:poke_id>/", views.poke_detail, name="poke-detail"),
    path("pokemon/<int:poke_id>/catch", views.catch_pokemon, name="catch-pokemon"),
    path("pokemon/show", views.show_pokemon, name="show-pokemon"),
    path(
        "pokemon/<int:pk>/delete/", views.PokemonDelete.as_view(), name="pokemon-delete"
    ),
    path(
        "pokemon/<int:poke_id>/update-nickname/",
        views.update_nickname,
        name="update-nickname",
    ),
    path("pokemon/<int:poke_id>/add-feeding/", views.add_feeding, name="add-feeding"),
    path("items/", views.ItemList.as_view(), name="items-index"),
    path("items/<int:pk>/", views.ItemDetail.as_view(), name="item-detail"),
    path("items/create/", views.ItemCreate.as_view(), name="item-create"),
    path("items/<int:pk>/update/", views.ItemUpdate.as_view(), name="item-update"),
    path("items/<int:pk>/delete/", views.ItemDelete.as_view(), name="item-delete"),
    path(
        "pokemon/<int:poke_id>/associate-item/<int:item_id>/",
        views.associate_item,
        name="associate-item",
    ),
    path('pokemon/<int:poke_id>/remove-item/<int:item_id>/', views.remove_item, name='remove-item'),

]

pokecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), # Mounts main_app's routes at the root URL
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ("A", "Apple"),
    ("B", "Berry"),
    ("G", "Grapes"),
    ("H", "Hot Dog"),
    ("P", "Pizza"),
    ("S", "Sushi"),
    ("T", "Tonkatsu"),
)

class Item(models.Model):
    name = models.CharField(max_length=100)
    effect = models.TextField(max_length=500)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("item-detail", kwargs={"pk": self.pk})
    


class Pokemon(models.Model):
    name = models.CharField(max_length=100)
    poke_id = models.IntegerField()
    xp = models.IntegerField()
    type = models.CharField(max_length=100)
    abilities = models.TextField()
    image_url = models.URLField()
    nickname = models.CharField(max_length=100, blank=True, null=True)
    items = models.ManyToManyField(Item)

    def __str__(self):
        return f"{self.name} (ID: {self.poke_id})"

    def get_absolute_url(self):
        return reverse("poke-detail", kwargs={"poke_id": self.poke_id})


class Feeding(models.Model):
    date = models.DateField("Feeding date")
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    pokemon = models.ForeignKey(
        Pokemon, on_delete=models.CASCADE, related_name="feedings"
    )

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ["-date"]

main_app/forms.py
from django import forms
from .models import Pokemon, Feeding


class PokemonNicknameForm(forms.ModelForm):
    class Meta:
        model = Pokemon
        fields = ["nickname"]


class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ["date", "meal"]
        widgets = {
            "date": forms.DateInput(
                format=("%Y-%m-%d"),
                attrs={"placeholder": "Select a date", "type": "date"},
            ),
        }

main_app/views.py
import random
import requests
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic import CreateView, ListView, DetailView
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound
from .models import Pokemon, Item
from .forms import PokemonNicknameForm, FeedingForm


def home(request):
    return render(request, "pokemon/home.html")


def about(request):
    return render(request, "about.html")


def index(request):
    def fetch_random_pokemon():
        random_index = random.randint(1, 150)
        response = requests.get(f"https://pokeapi.co/api/v2/pokemon/{random_index}/")
        if response.status_code == 200:
            data = response.json()
            name = data["name"].capitalize()
            poke_id = data["id"]
            xp = data["base_experience"]
            poke_type = data["types"][0]["type"]["name"]
            abilities = ", ".join(
                [ability["ability"]["name"] for ability in data["abilities"]]
            )
            image_url = data["sprites"]["other"]["official-artwork"]["front_default"]
            return {
                "name": name,
                "poke_id": poke_id,
                "xp": xp,
                "type": poke_type,
                "abilities": abilities,
                "image_url": image_url,
            }
        else:
            return None

    random_pokemon = fetch_random_pokemon()
    return render(request, "pokemon/index.html", {"pokemon": random_pokemon})


def poke_detail(request, poke_id):
    try:
        pokemon = Pokemon.objects.get(poke_id=poke_id)
        feeding_form = FeedingForm()
        items_pokemon_doesnt_have = Item.objects.exclude(id__in = pokemon.items.all().values_list('id'))

    except Pokemon.DoesNotExist:
        return HttpResponseNotFound("Pokemon not found")

    return render(
        request,
        "pokemon/detail.html",
        {
            "pokemon": pokemon,
            "feedings": pokemon.feedings.all(),
            "feeding_form": feeding_form,
            "items": items_pokemon_doesnt_have,
        },
    )


def catch_pokemon(request, poke_id):
    response = requests.get(f"https://pokeapi.co/api/v2/pokemon/{poke_id}/")

    if response.status_code == 200:
        data = response.json()
        name = data["name"].capitalize()
        poke_id = data["id"]
        xp = data["base_experience"]
        poke_type = data["types"][0]["type"]["name"]
        abilities = ", ".join(
            [ability["ability"]["name"] for ability in data["abilities"]]
        )
        image_url = data["sprites"]["other"]["official-artwork"]["front_default"]

        pokemon = Pokemon(
            name=name,
            poke_id=poke_id,
            xp=xp,
            type=poke_type,
            abilities=abilities,
            image_url=image_url,
        )

        pokemon.save()

        return redirect("show-pokemon")
    else:
        return HttpResponse("Error fetching data from the Pokémon API")


def show_pokemon(request):
    pokemon = Pokemon.objects.all()
    return render(request, "pokemon/show.html", {"pokemon": pokemon})


class PokemonDelete(DeleteView):
    model = Pokemon
    success_url = reverse_lazy("show-pokemon")


def update_nickname(request, poke_id):
    try:
        pokemon = Pokemon.objects.get(poke_id=poke_id)
    except Pokemon.DoesNotExist:
        return HttpResponseNotFound("Pokemon not found")

    if request.method == "POST":
        form = PokemonNicknameForm(request.POST, instance=pokemon)
        if form.is_valid():
            form.save()
            return redirect("show-pokemon")
    else:
        form = PokemonNicknameForm(instance=pokemon)

    return render(
        request, "pokemon/update_nickname.html", {"form": form, "pokemon": pokemon}
    )


def add_feeding(request, poke_id):
    try:
        pokemon = Pokemon.objects.get(poke_id=poke_id)
    except Pokemon.DoesNotExist:
        return HttpResponseNotFound("Pokemon not found")

    form = FeedingForm(request.POST)

    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.pokemon = pokemon
        new_feeding.save()
        return redirect("poke-detail", poke_id=poke_id)

    return render(
        request, "pokemon/add_feeding.html", {"form": form, "pokemon": pokemon}
    )

class ItemCreate(CreateView):
    model = Item
    fields = "__all__"

class ItemList(ListView):
    model = Item


class ItemDetail(DetailView):
    model = Item

class ItemUpdate(UpdateView):
    model = Item
    fields = ['name', 'effect']

class ItemDelete(DeleteView):
    model = Item
    success_url = '/items/'

def associate_item(request, poke_id, item_id):
    Pokemon.objects.get(poke_id=poke_id).items.add(item_id)
    return redirect('poke-detail', poke_id=poke_id)

def remove_item(request, poke_id, item_id):
    Pokemon.objects.get(poke_id=poke_id).items.remove(item_id)
    return redirect('poke-detail', poke_id=poke_id)

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Poke Collector</h1>
<hr />
<p class="page-content">
  The Pokemon Collector is a site where you can view and collect pokemon.
  <br>
  <br>
  You can view your Pokemon roster by clicking "Your Pokemon" in the navigation bar. 
  <br>
  <br>
  You can also view more information about the Pokemon by clicking on the Pokemon's card. 
  <br>
  If you would like to add a Pokemon to your collection, you can do so by clicking on the "Catch Pokemon" button on the Pokemon's page.
  <br>
  You can view all the Pokemon in your collection by clicking on the "My Collection" link in the navigation bar.
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% comment %} TODO: update Favicon {% endcomment %}
    <link rel="shortcut icon" type="image/png" href="" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Poke Collector</title>
    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img
            src="{% static 'images/pokemon/Poke-Collector-Top-Banner.png' %}"
            alt="The Poke Collector Logo"
          />
        </a>
      </div>
      <nav>
        <ul>
          <li><a href="/pokemon">Generate Random Pokemon</a></li>
          &nbsp;|&nbsp;
          <li><a href="/about">About</a></li>
          &nbsp;|&nbsp;
          <li><a href="/pokemon/show">Your Pokémon</a></li>
          &nbsp;|&nbsp;
          <li><a href="{% url 'item-create' %}">Add Item</a></li>
          &nbsp;|&nbsp;
          <li><a href="{% url 'items-index' %}">All Items</a></li>
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/index.html
{% extends "base.html" %} 
{% block title %} 
  Main Page 
{% endblock %} 
{% block body %}
<h1>Content!</h1>
{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Item?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'item-detail' item.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/items/item-detail.css' %}" />
{% endblock %} {% block content %}

<div class="card" style="border-color: {{ item.color }}">
  <div class="card-bg" style="background-color: {{ item.color }}"></div>
  <div class="card-content">
    <h2>{{ item.name }}</h2>
    <p>{{ item.effect }}</p>
  </div>
</div>
<a href="{% url 'item-update' item.id %}" class="btn warn">Edit</a>
<a href="{% url 'item-delete' item.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add Item</h1>
    {% endif %}
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/items/item-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Pokemon Items</h1>
</section>

<section class="card-container">
  {% for item in item_list %}
    <div class="card" style="border-color: {{ item.color }}">
      <div class="card-bg" style="background-color: {{ item.color }}"></div>
      <a href="{% url 'item-detail' item.id %}">
        <div class="card-content">
          <h2>{{ item.name }}</h2>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/main_app/poke_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h2>Are you sure you want to delete {{ object.name }}?</h2>
<form method="post">
  {% csrf_token %}
  <button type="submit">Confirm Delete</button>
</form>
<a href="{% url 'show-pokemon' %}">Cancel</a>
{% endblock %}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pokemon/poke-detail.css' %}" />
{% endblock %} {% block content %}

<section class="card-container">
  <div class="pokemon-card">
    <div class="pokemon-img-container">
      <img src="{{ pokemon.image_url }}" alt="{{ pokemon.name }}" />
    </div>
    <h2 class="pokemon-name">{{ pokemon.name }}</h2>
    <p><strong>Nickname:</strong> {{ pokemon.nickname }}</p>
    <p><strong>Experience:</strong> {{ pokemon.xp }}</p>
    <p><strong>Type:</strong> {{ pokemon.type }}</p>
    <p><strong>Abilities:</strong> {{ pokemon.abilities }}</p>
  </div>
</section>

<div class="feedings-item-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
      {% comment %} <img src="{% static 'images/pokemon-cone.svg' %}" alt="" />
      <img src="' %}" alt="" />
      <img src="" alt="" /> {% endcomment %}
    </div>
    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-feeding' pokemon.poke_id %}"
      method="post"
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %} {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Feeding</button>
    </form>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% if pokemon %}
        <tr>
          <td colspan="2">Pokemon: {{ pokemon.name }}</td>
        </tr>
        {% for feeding in pokemon.feeding_set.all %}
        <tr>
          <td>{{ feeding.date }}</td>
          <td>{{ feeding.get_meal_display }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="2">No feedings available.</td>
        </tr>
        {% endfor %} {% else %}
        <tr>
          <td colspan="2">No pokemon available.</td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </section>
  <section class="items">
      <h2>Items</h2>
    <h1>{{ pokemon.name }}'s Items</h1>
    
    <div class="subsection-content">
      {% if pokemon.items.count %} {% for item in pokemon.items.all %}
      <div class="item-container">
        <a href="{% url 'item-detail' item.id %}">
          <p>{{ item.name }}</p>
        </a>
        <form action="{% url 'remove-item' pokemon.poke_id item.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Remove Item</button>
        </form>
      </div>
      {% endfor %} {% else %}
      <p class="no-items">{{pokemon.name}} doesn't have any items!</p>
      {% endif %}
    </div>
    <h2>Available Items</h2>
    <div class="subsection-content">
      {% if items.count %} {% for item in items.all %}
      <div class="item-container">
        <a href="{% url 'item-detail' item.id %}">
          <p>A {{ item.color }} {{ item.name }}</p>
        </a>
        <form
          action="{% url 'associate-item' pokemon.poke_id item.id %}"
          method="post"
        >
          {% csrf_token %}
          <button type="submit" class="btn submit">Give item</button>
        </form>
      </div>
      {% endfor %} {% else %}
      <p class="all-items">
        {{pokemon.poke_id}} already has all the available items 🥳
      </p>
      {% endif %}
    </div>

    {% endblock %}
  </section>
</div>

main_app/templates/pokemon/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}" />
{% endblock %} {% block content %}
<section class="hero">
  <div class="hero-content">
    <h1>Welcome to Pokémon Collector</h1>
    <p>Catch 'em all and build your ultimate Pokémon collection!</p>
    <a href="/pokemon/generate" class="btn-primary">Generate Random Pokémon</a>
  </div>
  <div class="hero-img">
    <img src="{% static 'images/pokemon/hero.png' %}" alt="Pokémon heroes" />
  </div>
</section>

<section class="features">
  <div class="feature">
    <h2>Explore Your Collection</h2>
    <p>View all your collected Pokémon and manage your favorite ones.</p>
    <a href="/pokemon" class="btn-secondary">View Collection</a>
  </div>
  <div class="feature">
    <h2>About Pokémon Collector</h2>
    <p>
      Learn more about the app and how it helps you collect and discover
      Pokémon.
    </p>
    <a href="/about" class="btn-secondary">Learn More</a>
  </div>
</section>

<footer>
  <p>&copy; 2024 Pokémon Collector | Made with ❤️ by The Cave😎</p>
</footer>
{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pokemon/poke-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Random Pokemon Generator</h1>
  <img src="{% static 'images/pokemon/1.png' %}" alt="Red Pokeball" />
  <img src="{% static 'images/pokemon/2.png' %}" alt="Blue Pokeball" />
  <img src="{% static 'images/pokemon/3.png' %}" alt="A cool cat" />
  <img src="{% static 'images/pokemon/4.png' %}" alt="A cool cat" />
</section>

<section class="card-container">
  <div class="card">
    <div class="card-content">
      <div class="card-img-container">
        <img src="{{ pokemon.image_url }}" alt="{{ pokemon.name }}" />
      </div>
      <h2 class="card-title">{{ pokemon.name }}</h2>
      <p><strong>Experience:</strong> {{ pokemon.xp }}</p>
      <p><strong>Type:</strong> {{ pokemon.type }}</p>
      <p><strong>Abilities:</strong> {{ pokemon.abilities }}</p>
    </div>

    <a
      href="{% url 'catch-pokemon' pokemon.poke_id %}"
      class="btn btn-primary"
      id="catch-button"
    >
      <img
        class="pokeball-icon"
        src="/static/images/pokemon/1.png"
        alt="Red Pokeball"
      />
      Catch Pokémon
    </a>
  </div>
</section>

{% endblock %}

main_app/templates/pokemon/show.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pokemon/poke-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Your Pokémon Roster</h1>
</section>

<section class="card-container">
  {% for poke in pokemon %}
  <div class="card">
    <a href="{% url 'poke-detail' poke.poke_id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img src="{{ poke.image_url }}" alt="{{ poke.name }}" />
        </div>
        <h2 class="card-title">{{ poke.name }}</h2>
        <p><strong>Nickname:</strong> {{ poke.nickname }}</p>
        <p><strong>Experience:</strong> {{ poke.xp }}</p>
        <p><strong>Type:</strong> {{ poke.type }}</p>
        <p><strong>Abilities:</strong> {{ poke.abilities }}</p>
      </div>
    </a>
    <form
      action="{% url 'pokemon-delete' poke.pk %}"
      method="post"
      style="display: inline"
    >
      {% csrf_token %}
      <button type="submit" class="delete-button">Delete</button>
    </form>
    <a href="{% url 'update-nickname' poke.poke_id %}">Update Nickname</a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/pokemon/update_nickname.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/pokemon/update_nickname.css' %}"/>
{% endblock %}
{% block content %}

<h1>Update Nickname for {{ pokemon.name }}</h1>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}